services:
  api:
    container_name: openstream-api
    build: .
    restart: always
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - ${OPENSTREAM_VOL_PATH}:/usr/src/app/media/recordings
    environment:
      - KAFKA_BROKERS=kafka:9092
    networks:
      - octane-net

networks:
  octane-net:
    external: true
